name: malay_food_cal_tracker
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.3
  iconsax: ^0.0.8
  image_picker: ^1.0.7
  tflite_flutter: ^0.10.4
  image: ^4.1.7
  provider: ^6.1.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  firebase_core: ^2.24.2
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  path_provider: ^2.1.2
  flutter_image_compress: ^2.3.0
  google_fonts: 6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/resnet50_model6.tflite
    - assets/label3class.txt
    - assets/3classmodel_Trained1.tflite
    - assets/label6model.txt

flutter_icons:
  android: true
  image_path: "assets/applogo2.png"
