// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPxUwSXhZLiz8EYwCix6-RQ3KLBJNnU3I',
    appId: '1:181620501704:web:cad1adfec02de6b576c9fd',
    messagingSenderId: '181620501704',
    projectId: 'malay-food-cal-tracker',
    authDomain: 'malay-food-cal-tracker.firebaseapp.com',
    storageBucket: 'malay-food-cal-tracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlnxhqBoH8Nvbx20z8UKZbQOw8R-3mVfw',
    appId: '1:181620501704:android:85a9e4918debffeb76c9fd',
    messagingSenderId: '181620501704',
    projectId: 'malay-food-cal-tracker',
    storageBucket: 'malay-food-cal-tracker.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPxUwSXhZLiz8EYwCix6-RQ3KLBJNnU3I',
    appId: '1:181620501704:web:dc5c829a89546b8c76c9fd',
    messagingSenderId: '181620501704',
    projectId: 'malay-food-cal-tracker',
    authDomain: 'malay-food-cal-tracker.firebaseapp.com',
    storageBucket: 'malay-food-cal-tracker.appspot.com',
  );
}
